onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/clk
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_AN_PS_ACT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_AN_PS_Dummy
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_AN_PS_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_AN_PS_Local
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Air_AN
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Air_Grid
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_C2_RLY_EM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_C2_RLY_RESET
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_CA_PS_ACT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Card_POS
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_DC_PS_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_DR_AMP
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Door_PAMP
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_FAN_ACT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_FAN_OFF_Delay
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_FAN_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G1_PS_ACT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G1_PS_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G1_PS_Local
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G1_PS_OT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G2_PS_ACT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G2_PS_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G2_PS_Internal_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_G2_PS_Local
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_GR_SW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_HV_Connector
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_I_AN_HIGH_5A
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_I_AN_HIGH_6A
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_I_AN_PS_High
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_I_CA_HIGH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_I_G1_High
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_I_G2_HIGH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_LA_TEST
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_OT_AN_Ready
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_TUNE_OK_Delayed_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Temp_DR_AMP
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_U_AN_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_U_CA_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_U_G1_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_U_G2_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Water_AN
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/i_Water_Heat_EXCH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_ANY_HV_GO_OFF_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_ANY_SB_GO_OFF_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_C2_RLY_AN
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_C2_RLY_CA
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_C2_RLY_DRAC
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_C2_RLY_G1
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_C2_RLY_G2
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_CA_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_FAN_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_FULL_RF_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_HV_OFF_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_HV_ON_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_HV_Ready_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_AN_PS_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_AN_PS_Local
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_AN_PS_OC
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Air_Anode
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Air_Grid
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Alarm
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Anode_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Anode_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_CA_Delay
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Card_POS
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Cathode_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Cathode_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Control_Voltages
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_DR_AMP_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_DR_AMP_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Door_PAMP
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Dummy_AN_PS
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Emergency
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_FAN_OFF_Delay
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_FAN_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_FAN_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_G1_PS_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_G1_PS_OT
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_G1_PS_TEST
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_G2_PS_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_G2_PS_Internal_Fault
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_G2_PS_TEST
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_GR_SW_PAMP
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Grid2_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Grid2_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Grid_ON
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Grid_ON_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_HV_Connector
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_I_AN_HIGH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_I_CA_HIGH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_I_G1_HIGH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_I_G2_HIGH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_RF_Reduced
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Reduced_RF_PERM
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_TEMP_DR_AMP
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_U_AN_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_U_CA_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_U_G1_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_U_G2_LOW
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Water_Anode
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_LA_Water_Heat_EXCH
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_RED_RF_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_RF_PERM_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_RF_RED_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_SB_OFF_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_SB_ON_BAR
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/o_TH_AN_Ready
add wave -noupdate /RPSC_FPGA_TOP_Simulation_testbench/reset_test
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {249581095 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 177
configure wave -valuecolwidth 40
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {438732122 ps}
